/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.iut2.genconf.vue;

import fr.uga.iut2.genconf.modele.Conference;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author hippo
 */
public class VueConference extends javax.swing.JPanel {
    private final GUI gui;
    private Set<String> confsExistantes;
    JRadioButton [] boutonsConfs;
    
    
    /**
     * Creates new form VueConference
     */
    public VueConference(GUI gui) {
        this.gui = gui;
        this.confsExistantes = new HashSet<>(); 
        
        initComponents();
        contentPane(confsExistantes);
        
//        this.modifier.setEnabled(false);
//        this.voirPlus.setEnabled(false);
//        this.supConf.setEnabled(false);
    }

    public void setConfsExistantes(final Set<String> confsExistantes) {
        assert confsExistantes != null;
        this.confsExistantes = confsExistantes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conference = new javax.swing.JLabel();
        modifier = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        voirPlus = new javax.swing.JButton();
        confsPane = new javax.swing.JScrollPane();
        supConf = new javax.swing.JButton();

        conference.setText("Choisir la conférence : ");

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        voirPlus.setText("Voir plus...");
        voirPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirPlusActionPerformed(evt);
            }
        });

        supConf.setText("Supprimer conférence");
        supConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supConfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conference)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(annuler)
                                .addGap(18, 18, 18)
                                .addComponent(modifier))
                            .addComponent(supConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(voirPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conference)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voirPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supConf)
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addComponent(confsPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier)
                    .addComponent(annuler))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.gui.modifierConference(Optional.empty(), "");
    }//GEN-LAST:event_annulerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        for (JRadioButton uneConf : getContentPane()){
            if (uneConf.isSelected()){
                this.gui.toModifierConference(uneConf.getName());
                break;
            }
        }            
    }//GEN-LAST:event_modifierActionPerformed

    private void voirPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirPlusActionPerformed
        for (JRadioButton uneConf : getContentPane()){
            if (uneConf.isSelected()){
                this.gui.toVoirPlusSession(uneConf.getName());
                break;
            }
        }
    }//GEN-LAST:event_voirPlusActionPerformed

    private void supConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supConfActionPerformed
        for (JRadioButton uneConf : getContentPane()){
            if (uneConf.isSelected()){
                this.gui.supprimerConference(uneConf.getName());
                break;
            }
        }
    }//GEN-LAST:event_supConfActionPerformed

    private void contentPane(Set<String> confs){
        JRadioButton boutonConf;
        boutonsConfs = new JRadioButton[confs.size()];
        ButtonGroup confGroup = new ButtonGroup();
        int i = 0;
        for (String uneConf : confs){
            boutonConf = new JRadioButton(uneConf);
            boutonsConfs[i] = boutonConf;
            confGroup.add(boutonConf);
            confsPane.add(boutonConf);
            i++;
        }        
    }
    
    private JRadioButton[] getContentPane(){
        return boutonsConfs;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel conference;
    private javax.swing.JScrollPane confsPane;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supConf;
    private javax.swing.JButton voirPlus;
    // End of variables declaration//GEN-END:variables
}
