package fr.uga.iut2.genconf.vue;

import java.awt.Color;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import javax.swing.JSpinner;
import org.apache.commons.validator.routines.EmailValidator;
import fr.uga.iut2.genconf.modele.*;


public class VueCreationCommunication extends javax.swing.JPanel {
    private final GUI gui;
    private Set<String> communicationsExistantes;
    private boolean valideCorres, valideComm;
    private Session sess;

    /**
     * Creates new form VueCreationConference
     */
    public VueCreationCommunication(GUI gui) {
        this.gui = gui;
        this.communicationsExistantes = new HashSet<>();
        this.valideCorres = false;
        this.valideComm = false;

        // création de l'interface générée
        this.initComponents();

        // configuration des composants de l'interface (à faire après la création de l'interface)
        // format de date
        JSpinner.DateEditor editor = new JSpinner.DateEditor(
                this.dateDebut,
                "yyyy-MM-dd"
        );
        this.dateDebut.setEditor(editor);
        // désactivation du bouton de création
        this.creerButton.setEnabled(false);
    }

    public void setCommunicationsExistantes(final Set<String> communicationsExistantes) {
        assert communicationsExistantes != null;
        this.communicationsExistantes = communicationsExistantes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        communication = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomCommunication = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nbJours = new javax.swing.JSpinner();
        dateDebut = new javax.swing.JSpinner();
        label1 = new java.awt.Label();
        typeComm = new javax.swing.JComboBox<>();
        correspondant = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        corresNom = new javax.swing.JTextField();
        corresPrenom = new javax.swing.JTextField();
        corresEmail = new javax.swing.JTextField();
        creerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        creerCom = new javax.swing.JLabel();
        precedentButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        communication.setBorder(javax.swing.BorderFactory.createTitledBorder("Communication"));

        jLabel1.setText("Nom de la communication :");

        nomCommunication.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                verificationConference(evt);
            }
        });

        jLabel2.setText("Date de début :");

        jLabel3.setText("Durée (jour) :");

        nbJours.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        dateDebut.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Type communication :");

        typeComm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "keynote", "atelier", "article" }));

        javax.swing.GroupLayout communicationLayout = new javax.swing.GroupLayout(communication);
        communication.setLayout(communicationLayout);
        communicationLayout.setHorizontalGroup(
            communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communicationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, communicationLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomCommunication)
                            .addGroup(communicationLayout.createSequentialGroup()
                                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nbJours, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typeComm, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        communicationLayout.setVerticalGroup(
            communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communicationLayout.createSequentialGroup()
                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomCommunication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbJours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        correspondant.setBorder(javax.swing.BorderFactory.createTitledBorder("Correspondant"));

        jLabel4.setText("Nom :");

        jLabel5.setText("Prénom :");

        jLabel6.setText("Email :");

        corresNom.setName(""); // NOI18N
        corresNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificationAdmin(evt);
            }
        });

        corresPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificationAdmin(evt);
            }
        });

        corresEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificationAdmin(evt);
            }
        });

        javax.swing.GroupLayout correspondantLayout = new javax.swing.GroupLayout(correspondant);
        correspondant.setLayout(correspondantLayout);
        correspondantLayout.setHorizontalGroup(
            correspondantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(correspondantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(correspondantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(correspondantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corresNom, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(corresPrenom)
                    .addComponent(corresEmail))
                .addContainerGap())
        );
        correspondantLayout.setVerticalGroup(
            correspondantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(correspondantLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(correspondantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(corresNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(correspondantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(corresPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(correspondantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(corresEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        corresNom.getAccessibleContext().setAccessibleName("corresNom");

        creerButton.setText("Créer");
        creerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        creerCom.setText("Créer une communication");

        precedentButton.setText("Precedent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correspondant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(communication, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creerCom)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precedentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(annulerButton)
                        .addGap(18, 18, 18)
                        .addComponent(creerButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creerCom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(communication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(correspondant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precedentButton)
                    .addComponent(annulerButton)
                    .addComponent(creerButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerButtonActionPerformed
         IHM.InfosUtilisateur corres = new IHM.InfosUtilisateur(
                this.corresEmail.getText().trim().toLowerCase(),
                this.corresNom.getText().trim(),
                this.corresPrenom.getText().trim()
         );

         // Traitement des dates de début et fin
         Date debut = (Date) this.dateDebut.getModel().getValue();
         LocalDate dateDebut = Instant.ofEpochMilli(debut.getTime())
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate();
         LocalDate dateFin = dateDebut.plusDays((Integer) nbJours.getValue() - 1);

         // Infos sur la nouvelle conference
         IHM.InfosCommunication nlleComm = new IHM.InfosCommunication(
                 this.nomCommunication.getText(),
                 this.typeComm.getActionCommand(),
                 dateDebut,
                 dateFin,
                 corres,
                 sess
         );

         this.gui.creerCommunication(Optional.of(nlleComm));
    }//GEN-LAST:event_creerButtonActionPerformed

    private void verificationCorres(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificationAdmin
        boolean validEmail;
        String nom, prenom;
        EmailValidator validator = EmailValidator.getInstance(false, false);

        nom = this.corresNom.getText().trim();
        prenom = this.corresPrenom.getText().trim();
        validEmail = validator.isValid(this.corresEmail.getText().trim().toLowerCase());
        this.corresEmail.setForeground(validEmail ? Color.black : Color.red);

        this.valideCorres = validEmail
                 && (nom != null) && (nom.length() > 0)
                 && (prenom != null) && (prenom.length() > 0);

        this.creerButton.setEnabled(this.valideCorres && this.valideComm);
    }//GEN-LAST:event_verificationAdmin

    private void verificationCommunication(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificationConference
         this.valideComm = !communicationsExistantes.contains(nomCommunication.getText());
         this.nomCommunication.setForeground(this.valideComm ? Color.black : Color.red);
         this.creerButton.setEnabled(this.valideCorres && this.valideComm);
    }//GEN-LAST:event_verificationConference

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.gui.creerCommunication(Optional.empty());
    }//GEN-LAST:event_annulerButtonActionPerformed
    
    private void precedentButtonActionPerformed(java.awt.event.ActionEvent evt){
        this.gui.toVoirPlusCommunication(sess.getNom());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JPanel communication;
    private javax.swing.JTextField corresEmail;
    private javax.swing.JTextField corresNom;
    private javax.swing.JTextField corresPrenom;
    private javax.swing.JPanel correspondant;
    private javax.swing.JButton creerButton;
    private javax.swing.JLabel creerCom;
    private javax.swing.JSpinner dateDebut;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.Label label1;
    private javax.swing.JSpinner nbJours;
    private javax.swing.JTextField nomCommunication;
    private javax.swing.JButton precedentButton;
    private javax.swing.JComboBox<String> typeComm;
    // End of variables declaration//GEN-END:variables
}
