package fr.uga.iut2.genconf.vue;

import java.awt.Color;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import javax.swing.JSpinner;
import org.apache.commons.validator.routines.EmailValidator;
import fr.uga.iut2.genconf.util.Type;


public class VueCreationSession extends javax.swing.JPanel {
    private final GUI gui;
    private Set<String> nomsExistants;
    private boolean valideAnim, valideSess;

    /**
     * Creates new form VueCreationConference
     */
    public VueCreationSession(GUI gui) {
        this.gui = gui;
        this.nomsExistants = new HashSet<>();
        this.valideAnim = false;
        this.valideSess = false;

        // création de l'interface générée
        this.initComponents();

        // configuration des composants de l'interface (à faire après la création de l'interface)
        // format de date
        JSpinner.DateEditor editor = new JSpinner.DateEditor(
                this.dateDebut,
                "yyyy-MM-dd"
        );
        this.dateDebut.setEditor(editor);
        // désactivation du bouton de création
        this.creerButton.setEnabled(false);
    }

    public void setNomsExistants(final Set<String> nomsExistants) {
        assert nomsExistants != null;
        this.nomsExistants = nomsExistants;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        Session = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomSess = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nbJours = new javax.swing.JSpinner();
        dateDebut = new javax.swing.JSpinner();
        typeSess = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        saisieAdminPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        animNom = new javax.swing.JTextField();
        animPrenom = new javax.swing.JTextField();
        animEmail = new javax.swing.JTextField();
        creerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        precedentButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Session.setBorder(javax.swing.BorderFactory.createTitledBorder("Session"));

        jLabel1.setText("Nom de la session :");

        nomSess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomSessActionPerformed(evt);
            }
        });
        nomSess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                verificationConference(evt);
            }
        });

        jLabel2.setText("Date de début :");

        jLabel3.setText("Durée (jour) :");

        nbJours.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        dateDebut.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        typeSess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "keynote", "atelier", "article" }));

        jLabel8.setText("Type de la session :");

        javax.swing.GroupLayout SessionLayout = new javax.swing.GroupLayout(Session);
        Session.setLayout(SessionLayout);
        SessionLayout.setHorizontalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomSess)
                    .addGroup(SessionLayout.createSequentialGroup()
                        .addGroup(SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nbJours, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeSess, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 209, Short.MAX_VALUE))))
        );
        SessionLayout.setVerticalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionLayout.createSequentialGroup()
                .addGroup(SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomSess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbJours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(typeSess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        saisieAdminPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Anima·teur/trice"));

        jLabel4.setText("Nom :");

        jLabel5.setText("Prénom :");

        jLabel6.setText("Email :");

        animNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificationAdmin(evt);
            }
        });

        animPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificationAdmin(evt);
            }
        });

        animEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificationAdmin(evt);
            }
        });

        javax.swing.GroupLayout saisieAdminPanelLayout = new javax.swing.GroupLayout(saisieAdminPanel);
        saisieAdminPanel.setLayout(saisieAdminPanelLayout);
        saisieAdminPanelLayout.setHorizontalGroup(
            saisieAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saisieAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saisieAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saisieAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(animNom)
                    .addComponent(animPrenom)
                    .addComponent(animEmail))
                .addContainerGap())
        );
        saisieAdminPanelLayout.setVerticalGroup(
            saisieAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saisieAdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(saisieAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(animNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saisieAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(animPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saisieAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(animEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        creerButton.setText("Créer");
        creerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Créer une session");

        precedentButton.setText("Precedent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saisieAdminPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(precedentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(annulerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saisieAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerButton)
                    .addComponent(creerButton)
                    .addComponent(precedentButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerButtonActionPerformed
         IHM.InfosUtilisateur anim = new IHM.InfosUtilisateur(
                this.animEmail.getText().trim().toLowerCase(),
                this.animNom.getText().trim(),
                this.animPrenom.getText().trim()
         );

         // Traitement des dates de début et fin
         Date debut = (Date) this.dateDebut.getModel().getValue();
         LocalDate dateDebut = Instant.ofEpochMilli(debut.getTime())
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate();
         LocalDate dateFin = dateDebut.plusDays((Integer) nbJours.getValue() - 1);

         // Infos sur la nouvelle conference
         IHM.InfosSession nlleSess = new IHM.InfosSession(
                 this.nomSess.getText(),
                 this.typeSess.getActionCommand(),
                 dateDebut,
                 dateFin,
                 anim
         );

         this.gui.creerSession(Optional.of(nlleSess));
    }//GEN-LAST:event_creerButtonActionPerformed

    private void verificationAdmin(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificationAdmin
        boolean validEmail;
        String nom, prenom;
        EmailValidator validator = EmailValidator.getInstance(false, false);

        nom = this.animNom.getText().trim();
        prenom = this.animPrenom.getText().trim();
        validEmail = validator.isValid(this.animEmail.getText().trim().toLowerCase());
        this.animEmail.setForeground(validEmail ? Color.black : Color.red);

        this.valideAnim = validEmail
                 && (nom != null) && (nom.length() > 0)
                 && (prenom != null) && (prenom.length() > 0);

        this.creerButton.setEnabled(this.valideAnim&& this.valideSess);
    }//GEN-LAST:event_verificationAdmin

    private void verificationConference(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificationConference
         this.valideSess = !nomsExistants.contains(nomSess.getText());
         this.nomSess.setForeground(this.valideSess ? Color.black : Color.red);
         this.creerButton.setEnabled(this.valideAnim && this.valideSess);
    }//GEN-LAST:event_verificationConference

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.gui.creerConference(Optional.empty());
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void nomSessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomSessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomSessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Session;
    private javax.swing.JTextField animEmail;
    private javax.swing.JTextField animNom;
    private javax.swing.JTextField animPrenom;
    private javax.swing.JButton annulerButton;
    private javax.swing.JButton creerButton;
    private javax.swing.JSpinner dateDebut;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner nbJours;
    private javax.swing.JTextField nomSess;
    private javax.swing.JButton precedentButton;
    private javax.swing.JPanel saisieAdminPanel;
    private javax.swing.JComboBox<String> typeSess;
    // End of variables declaration//GEN-END:variables
}
