/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.iut2.genconf.vue;

import fr.uga.iut2.genconf.modele.Conference;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author hippo
 */
public class VueConference extends javax.swing.JPanel {
    private final GUI gui;
    private Set<String> confsExistantes;
    JRadioButton [] boutonsConfs;
    
    /**
     * Creates new form VueConference
     */
    public VueConference(GUI gui) {
        this.gui = gui;
        this.confsExistantes = new HashSet<>(); 
        
        initComponents();        
    }

    public void setConfsExistantes(final Set<String> confsExistantes) {
        assert confsExistantes != null;
        this.confsExistantes = confsExistantes;
        contentPane(confsExistantes);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        conference = new javax.swing.JLabel();
        modifier = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        voirPlus = new javax.swing.JButton();
        supConf = new javax.swing.JButton();
        confsPane = new javax.swing.JScrollPane();
        listConfs = new javax.swing.JList<>();

        conference.setText("Choisir la conférence : ");

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        voirPlus.setText("Voir plus...");
        voirPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirPlusActionPerformed(evt);
            }
        });

        supConf.setText("Supprimer conférence");
        supConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supConfActionPerformed(evt);
            }
        });

        listConfs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        confsPane.setViewportView(listConfs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conference)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supConf, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voirPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(annuler)
                        .addGap(18, 18, 18)
                        .addComponent(modifier)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(conference)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voirPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supConf)
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(confsPane))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier)
                    .addComponent(annuler))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.gui.modifierConference(Optional.empty(), "");
    }//GEN-LAST:event_annulerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
//        for (JRadioButton uneConf : getContentPane()){
//            if (uneConf.isSelected()){
//                
//                break;
//            }
//        }
        this.gui.toModifierConference(this.listConfs.getSelectedValue());
    }//GEN-LAST:event_modifierActionPerformed

    private void voirPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirPlusActionPerformed
        this.gui.toVoirPlusSession(this.listConfs.getSelectedValue());
    }//GEN-LAST:event_voirPlusActionPerformed

    private void supConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supConfActionPerformed
        this.gui.supprimerConference(this.listConfs.getSelectedValue());
    }//GEN-LAST:event_supConfActionPerformed

    private void contentPane(Set<String> confs){  
        listConfs.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String> strings = new ArrayList(confs);
            public int getSize() { return strings.size(); }
            public String getElementAt(int i) { return strings.get(i); }
        });      
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel conference;
    private javax.swing.JScrollPane confsPane;
    private javax.swing.JList<String> listConfs;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supConf;
    private javax.swing.JButton voirPlus;
    // End of variables declaration//GEN-END:variables
}
