/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.iut2.genconf.vue;

import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author hippo
 */
public class VueCommunication extends javax.swing.JPanel {
    private final GUI gui;
    private Set<String> comsExistantes;
    JRadioButton [] boutonsComs;

    /**
     * Creates new form VueConference
     */
    public VueCommunication(GUI gui) {
        this.gui = gui;
        this.comsExistantes = new HashSet<>();
        
        initComponents();
        contentPane(getListeCommunications());
    }
        
    public void setComsExistantes(final Set<String> comsExistantes) {
        assert comsExistantes != null;
        this.comsExistantes = comsExistantes;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Communication = new javax.swing.JLabel();
        modifier = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        comsPane = new javax.swing.JScrollPane();
        conférence = new javax.swing.JLabel();
        CreerCom = new javax.swing.JButton();
        Précedent = new javax.swing.JButton();
        Session = new javax.swing.JLabel();
        supCom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Communication.setText("Choisir la communication : ");

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        conférence.setText("Pour la conférence .");

        CreerCom.setText("Creer communication");
        CreerCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerComActionPerformed(evt);
            }
        });

        Précedent.setText("Precedent");

        Session.setText("Pour la session .");

        supCom.setText("Supprimer communication");
        supCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supComActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Précedent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(annuler)
                        .addGap(18, 18, 18)
                        .addComponent(modifier))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Communication)
                            .addComponent(conférence)
                            .addComponent(Session))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreerCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(conférence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Session)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Communication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier)
                            .addComponent(annuler)
                            .addComponent(Précedent)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreerCom)
                        .addGap(18, 18, 18)
                        .addComponent(supCom)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.gui.modifierCommunication(Optional.empty());
    }//GEN-LAST:event_annulerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        for (JRadioButton uneCom : getContentPane()){
            if (uneCom.isSelected()){
                this.gui.toModifierCommunication(uneCom.getName());
                break;
            }
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void CreerComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerComActionPerformed
            this.gui.saisirNouvelleCommunication(this.comsExistantes);            
    }//GEN-LAST:event_CreerComActionPerformed

    private void supComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supComActionPerformed
        for (JRadioButton uneCom : getContentPane()){
            if (uneCom.isSelected()){
                this.gui.supprimerCommunication(uneCom.getName());
                break;
            }
        }
    }//GEN-LAST:event_supComActionPerformed

    /**
     * @param args the command line arguments
     */
    private void contentPane(Set<String> coms){
        JRadioButton boutonCom;
        boutonsComs = new JRadioButton[coms.size()];
        ButtonGroup confGroup = new ButtonGroup();
        int i = 0;
        for (String uneConf : coms){
            boutonCom = new JRadioButton(uneConf);
            boutonsComs[i] = boutonCom;
            confGroup.add(boutonCom);
            comsPane.add(boutonCom);
            i++;
        }        
    }
    
    private JRadioButton[] getContentPane(){
        return boutonsComs;
    }
    

        
    
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Communication;
    private javax.swing.JButton CreerCom;
    private javax.swing.JButton Précedent;
    private javax.swing.JLabel Session;
    private javax.swing.JButton annuler;
    private javax.swing.JScrollPane comsPane;
    private javax.swing.JLabel conférence;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supCom;
    // End of variables declaration//GEN-END:variables
}
