/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.iut2.genconf.vue;

import java.awt.Color;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Optional;
import fr.uga.iut2.genconf.modele.*;
import java.util.Iterator;

/**
 *
 * @author hippo
 */
public class VueModifierSession extends javax.swing.JPanel {
    private final GUI gui;
    private Set<String> sessionsExistantes;
    private boolean valideSess;
    private Conference conf;
    private Session session;
    /**
     * Creates new form VueModifierSession
     */
    public VueModifierSession(GUI gui) {
        this.gui = gui;
        this.sessionsExistantes = new HashSet();
        this.valideSess = false;
        
        initComponents();
        
    }
    
    public void setSessionsExistantes(final Set<String> sessionsExistantes) {
        assert sessionsExistantes != null;
        this.sessionsExistantes = sessionsExistantes;
    }
    
    public void setConf(Conference conf){
        this.conf = conf;
    }
    
    public void setSession(Session s){
        this.session = s;
        this.labelSession.setText(this.labelSession.getText()+this.session.getNom());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneSession = new javax.swing.JPanel();
        nomSession = new java.awt.Label();
        labelDateDebut = new java.awt.Label();
        labelDateFin = new java.awt.Label();
        textFieldNom = new java.awt.TextField();
        jSpinnerDateDebut = new javax.swing.JSpinner();
        jSpinnerDateFin = new javax.swing.JSpinner();
        labelSession = new java.awt.Label();
        precedent = new javax.swing.JButton();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        buttonSupprAnim = new java.awt.Button();
        buttonAddAnim = new java.awt.Button();

        jPaneSession.setBorder(javax.swing.BorderFactory.createTitledBorder("Session"));

        nomSession.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nomSession.setText("Nom :");

        labelDateDebut.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelDateDebut.setText("Date de début :");

        labelDateFin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelDateFin.setText("Date de fin :");

        textFieldNom.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificationSession(evt);
            }
        });

        jSpinnerDateDebut.setModel(new javax.swing.SpinnerDateModel());

        jSpinnerDateFin.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPaneSessionLayout = new javax.swing.GroupLayout(jPaneSession);
        jPaneSession.setLayout(jPaneSessionLayout);
        jPaneSessionLayout.setHorizontalGroup(
            jPaneSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPaneSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPaneSessionLayout.createSequentialGroup()
                        .addGroup(jPaneSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPaneSessionLayout.setVerticalGroup(
            jPaneSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSessionLayout.createSequentialGroup()
                .addGroup(jPaneSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneSessionLayout.createSequentialGroup()
                        .addComponent(labelDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneSessionLayout.createSequentialGroup()
                        .addComponent(jSpinnerDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        nomSession.getAccessibleContext().setAccessibleName("Nom session");
        labelDateFin.getAccessibleContext().setAccessibleName("date de fin :");

        labelSession.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelSession.setText("Modifier la session");

        precedent.setText("Precedent");
        precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedentActionPerformed(evt);
            }
        });

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        buttonSupprAnim.setLabel("Supprimer animateur");
        buttonSupprAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprAnimActionPerformed(evt);
            }
        });

        buttonAddAnim.setLabel("Ajouter animateur");
        buttonAddAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAnimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSession, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPaneSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precedent)
                        .addGap(169, 169, 169)
                        .addComponent(annuler)
                        .addGap(18, 18, 18)
                        .addComponent(valider)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(buttonSupprAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAddAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSupprAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAddAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(annuler)
                            .addComponent(precedent)
                            .addComponent(valider))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelSession.getAccessibleContext().setAccessibleName("Modifier la session");
    }// </editor-fold>//GEN-END:initComponents

    private void precedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedentActionPerformed
        this.gui.toVoirPlusSession(this.conf.getNom());
    }//GEN-LAST:event_precedentActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.gui.modifierSession(Optional.empty(), this.session.getNom());
    }//GEN-LAST:event_annulerActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // Traitement des dates de début et fin
        Date debut = (Date) this.jSpinnerDateDebut.getModel().getValue();
        LocalDate dateDebut = Instant.ofEpochMilli(debut.getTime())
                                     .atZone(ZoneId.systemDefault())
                                     .toLocalDate();
        
        debut = (Date) this.jSpinnerDateFin.getModel().getValue();
        LocalDate dateFin = Instant.ofEpochMilli(debut.getTime())
                                     .atZone(ZoneId.systemDefault())
                                     .toLocalDate();
        
        // Iterateur sur les animateurs -> récupérer anim session
        Iterator it = session.getAnimateurs().values().iterator();
        Utilisateur user = new Utilisateur(null, null, null);
        while(it.hasNext()){
            user = (Utilisateur) it.next();
            break;
        }
        
        IHM.InfosUtilisateur anim = new IHM.InfosUtilisateur(
               user.getEmail(),
               user.getNom(),
               user.getPrenom()
        );
        
        // Infos sur la nouvelle conference
        IHM.InfosSession session = new IHM.InfosSession(
                this.textFieldNom.getText(),
                this.session.getType().toString(),
                dateDebut,
                dateFin,
                anim,
                conf
        );
         
        this.gui.modifierSession(Optional.of(session), this.session.getNom());
    }//GEN-LAST:event_validerActionPerformed

    private void buttonSupprAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprAnimActionPerformed
        this.gui.toSupprimerAnimateur(this.session.getNom(), this.conf.getNom());
    }//GEN-LAST:event_buttonSupprAnimActionPerformed

    private void buttonAddAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAnimActionPerformed
        this.gui.toAjouterAnimateur(this.session.getNom(), this.conf.getNom());
    }//GEN-LAST:event_buttonAddAnimActionPerformed

    private void verificationSession(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificationSession
        this.valideSess = !sessionsExistantes.contains(textFieldNom.getText().trim()) || (textFieldNom.getText().trim() == this.session.getNom());
        this.textFieldNom.setForeground(this.valideSess ? Color.black : Color.red);
        this.valider.setEnabled(valideSess);
    }//GEN-LAST:event_verificationSession

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private java.awt.Button buttonAddAnim;
    private java.awt.Button buttonSupprAnim;
    private javax.swing.JPanel jPaneSession;
    private javax.swing.JSpinner jSpinnerDateDebut;
    private javax.swing.JSpinner jSpinnerDateFin;
    private java.awt.Label labelDateDebut;
    private java.awt.Label labelDateFin;
    private java.awt.Label labelSession;
    private java.awt.Label nomSession;
    private javax.swing.JButton precedent;
    private java.awt.TextField textFieldNom;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
