/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.iut2.genconf.vue;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;

/**
 *
 * @author hippo
 */
public class VueSession extends javax.swing.JPanel {
    private final GUI gui;
    private Set<String> sessionsExistantes;
    private String nomConf;
    private boolean valide;
    /**
     * Creates new form VueConference
     */
    public VueSession(GUI gui) {
        this.gui = gui;
        this.sessionsExistantes = new HashSet();
        
        initComponents();
        this.modifier.setEnabled(false);
        this.voirPlus.setEnabled(false);
        this.supSession.setEnabled(false);
    }

    public void setSessionsExistantes(final Set<String> sessionsExistantes) {
        assert sessionsExistantes != null;
        this.sessionsExistantes = sessionsExistantes;
        contentPane(sessionsExistantes);        
    }
    
    public void setConf(String nomConf){
        this.nomConf = nomConf;
        this.labelConf.setText("Pour la conférence : "+this.nomConf);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        modifier = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        voirPlus = new javax.swing.JButton();
        sessionsPane = new javax.swing.JScrollPane();
        listSessions = new javax.swing.JList<>();
        labelConf = new javax.swing.JLabel();
        creerSession = new javax.swing.JButton();
        precedent = new javax.swing.JButton();
        supSession = new javax.swing.JButton();

        jLabel1.setText("Choisir la session : ");

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        voirPlus.setText("Voir plus...");
        voirPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirPlusActionPerformed(evt);
            }
        });

        listSessions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSessionsMouseClicked(evt);
            }
        });
        sessionsPane.setViewportView(listSessions);

        labelConf.setText("Pour la conférence ");

        creerSession.setText("Creer session");
        creerSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerSessionActionPerformed(evt);
            }
        });

        precedent.setText("Precedent");
        precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedentActionPerformed(evt);
            }
        });

        supSession.setText("Supprimer session");
        supSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precedent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(annuler)
                        .addGap(18, 18, 18)
                        .addComponent(modifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sessionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creerSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(voirPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supSession)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(labelConf))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(labelConf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voirPlus)
                        .addGap(18, 18, 18)
                        .addComponent(creerSession)
                        .addGap(18, 18, 18)
                        .addComponent(supSession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier)
                            .addComponent(annuler)
                            .addComponent(precedent)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sessionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.gui.modifierSession(Optional.empty(), "");
    }//GEN-LAST:event_annulerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        this.gui.toModifierSession(this.listSessions.getSelectedValue(), this.nomConf);
    }//GEN-LAST:event_modifierActionPerformed

    private void voirPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirPlusActionPerformed
        this.gui.toVoirPlusCommunications(this.listSessions.getSelectedValue(), this.nomConf);
    }//GEN-LAST:event_voirPlusActionPerformed

    private void supSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supSessionActionPerformed
        this.gui.supprimerSession(this.listSessions.getSelectedValue(), this.nomConf); 
    }//GEN-LAST:event_supSessionActionPerformed

    private void creerSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerSessionActionPerformed
        this.gui.saisirNouvelleSession(this.nomConf);
    }//GEN-LAST:event_creerSessionActionPerformed

    private void precedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedentActionPerformed
        this.gui.actionModifierConference();
    }//GEN-LAST:event_precedentActionPerformed

    private void listSessionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSessionsMouseClicked
        valide = !this.listSessions.isSelectionEmpty(); 
        this.modifier.setEnabled(valide);
        this.voirPlus.setEnabled(valide);
        this.supSession.setEnabled(valide);
    }//GEN-LAST:event_listSessionsMouseClicked

    private void contentPane(Set<String> sessions){
        listSessions.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String> strings = new ArrayList(sessions);
            public int getSize() { return strings.size(); }
            public String getElementAt(int i) { return strings.get(i); }
        });         
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JButton creerSession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelConf;
    private javax.swing.JList<String> listSessions;
    private javax.swing.JButton modifier;
    private javax.swing.JButton precedent;
    private javax.swing.JScrollPane sessionsPane;
    private javax.swing.JButton supSession;
    private javax.swing.JButton voirPlus;
    // End of variables declaration//GEN-END:variables
}
